export const articles = {
  FETCH_REQUEST_ARTICLES: 'FETCH_REQUEST_ARTICLES',
  FETCH_RECEIVE_ARTICLES: 'FETCH_RECEIVE_ARTICLES',
  FETCH_FAILURE_ARTICLES: 'FETCH_FAILURE_ARTICLES',
}

export const baseUrl = {
  url: 'https://conduit.productionready.io/api/',
  sign_up: 'users',
  login: 'login',
}

export const registration = {
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_WRONG: 'SIGN_UP_WRONG',
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_WRONG: 'SIGN_IN_WRONG',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_WRONG: 'LOGIN_WRONG',
  LOG_OUT: 'LOG_OUT',
  UPDATE_USER: 'UPDATE_USER',
}

export const modal = {
  OPENED: 'OPEN',
  CLOSED: 'CLOSED'
}